examples/supercollider-with-acoustic-instruments-examples.md

Fixed markdown for links to display properly; added a few more pieces to the list.

Add piece examples, fix links

---

examples/supercollider-with-acoustic-instruments-examples.md

Off<>zz and Bo is Burning are two ensembles that heavily rely on supercollider. Off<>zz is a laptop and piano/toypiano duo exploring electro-acoustic music via improvisation, live coding, and transformation of classical-music influences. Bo is burning is a duo exploring music theatre and movement with live-electronics and contemporary clog dancing.

Added examples of supercollider with performances

---

examples/supercollider-with-acoustic-instruments-examples.md

Shorten the description on the duo and the presented works.

Update Bo is Burning

---

development/git-cheat-sheet.md

As discussed under issue
https://github.com/supercollider/supercollider/issues/1781#issuecomment-
170959978 and suggested notably by @miguel-negrao this is my
contribution to the SC
"git-cheat-sheet" (http://supercollider.github.io/development/git-cheat-sheet.html).

Add git user model to 'git-cheat-sheet'

---

.travis.yml
Gemfile
script/cibuild

Should run travis on each commit to master or PR. 
Updated Gemfile to currently documented state.
Htmlproofer produces tons of errors on links, so I didn't add it.
Worth it?

Add travis and update Gemfile

---

_posts/2016-07-09-supercollider-3.7.2.md

let me know if anything's missing...
@crucialfelix

Announce 3.7 - 3.7.2

---

contributing/index.md

I made some additions to the Contributing page and I think the page is valuable enough to go in the main nav.

Add "Contributing" to navigation

---

index.md

Discussed here: https://github.com/supercollider/supercollider/issues/2263

Update SC description

---

development/building-raspberrypi.md

As more and more users are building on rpi, I thought those (cosmetic) changes might be worth it as it makes the process slightly simpler.

Simplify build instructions for rpi

---

index.md

This commit adds a focus on areas in which SuperCollider is strong, but were so far omitted.

Add focus on some features

---

community/systems-interfacing-with-sc.md

clients page: update link

---

index.md

see https://github.com/supercollider/supercollider/pull/3090

replace gitter badge with slack badge

---

contributing/index.md

This page needed updating with regards to our adoption of git-flow. I know that our `master` branch isn't stable at the moment. Maybe I should mention this? I also fixed a broken link to our git workflow.
Please post your suggestions here. I'll be happy to make all necessary changes.

Updated page to reflect git-flow

---

development/bugs.md

Replacing `master` branch with `develop`.

Replaced master with develop

---

development/building-raspberrypi.md

a few minor changes, more benchmarks, added important note about dithering

update rpi build instructions for stretch 2

---

_includes/download.md

Open to debate, it's also kind of funny to keep them.

correct links, separate source and binaries

---

_includes/download.md

This is my attempt at improving the Download page. Feedback and review welcomed!

Update Download page

---

_includes/download.md

Instead of master (master is stable now)

Downloads: link to develop branch builds

---

index.md

See https://github.com/supercollider/supercollider/pull/3389

Add new slack join link

---

_includes/download.md

I think this was all that was needed.

Add missing element </p> to Downloads page

---

_includes/download.md

Open to debate, it's also kind of funny to keep them.

remove os icons, because they look outdated

---

development/building-beagleboneblack.md

removed the steps for moving GUI files

Beaglebone instruction updates for 3.9.1

---

development/building-beagleboneblack.md

Add note about >=3.9.1

---

index.md

visuals are good, but not misleading ones. i don't think a screenshot of an unmaintained macOS-only quark is very representative of SC.

Remove screenshot

---

tutorials/error-primitive-basicnew-failed.md

For https://github.com/supercollider/supercollider.github.io/projects/1#card-1525762

wiki: migrate error primitive basicnew page

---

index.md

This PR is a fix for the issues that were introduced by #142. I'm sorry that I merge that PR without noticing these mistakes. Hopefully, they are all fixed. 
Over all, the homepage is now in better shape thanks to #142 and this PR.
**Note: ** I haven't built this locally, unfortunately. Review with care.

Fix issues introduced with Markdown redesign PR

---

examples/supercollider-code-examples.md

try github markdown for code

---

examples/supercollider-code-examples.md

Let's revert this back to how it was previously.

Revert code highlighting

---

download.md

The markdown redesign continues...

Download page markdown redesign

---

_layouts/default.html

otherwise they don't appear under new settings

Make badges https

---

index.md

This PR adds some horizontal rules to the homepage to help separate the different sections. A very slight improvement.

Add horizontal rules to homepage

---

development/building-beagleboneblack.md
development/building-raspberrypi.md

This is an update to the Rpi and BBB build guides for SC 3.9.2 and higher.

Add note about .config/ directory on SC 3.9.2+

---

_includes/download.md
_posts/2018-03-23-supercollider-3.9.2.md

- Post for 3.9.2
- Change 3.9.1 download links to 3.9.2

Update site for 3.9.2 release

---

index.md

[docs] - supercollider/supercollider.github.io/index.md - fixing tiny little details (punctuation, grammar, spelling, etc.)

[docs] - supercollider/supercollider.github.io/index.md - fixing tiny little details (punctuation, grammar, spelling, etc.)

---

README.md

[docs] - supercollider/suppercollider.github.io/README.md - fixing tiny little issues (grammar, spelling, ponctuation, etc.)
cheers

[docs] - supercollider/suppercollider.github.io/README.md - fixing tiny little issues (grammar, spelling, ponctuation, etc.)

---

tutorials/index.md

Update Tutorial List with link to Spanish Coursera SuperCollider Course.

Update Tutorial List with link to Spanish Course

---

contributing/index.md

I was not able to execute the command the way it was previously written without the .git extension

Updating the git url to include the .git extension

---

css/main.css

fix layout bug introduced in #185

---

_includes/download.md

Update version to 3.10.2

---

development/git-cheat-sheet.md

Updated version of stale PR #195

fix link to pro git book

---

development/building-beagleboneblack.md
development/building-raspberrypi.md

mainly for Buster and to turn off QTWEBENGINE.  also a few cosmetics and updated benchmarks.

updates for 3.10

---

community/systems-interfacing-with-sc.md

Add link to python-supercollider module

Add python-supercollider to Systems Interfacing with SC

---

index.md

Matches https://github.com/supercollider/supercollider/pull/4635

Add info about RFCs

---

index.md

updated Slack invite link based on issue #209 link provided by @brianlheim

updated Slack invite link

---

_includes/download.md

Checked locally and all the links work. Please review carefully though.

Update download page for 3.11.1

---

_layouts/default.html
contributing/index.md
development/building.md
development/git-cheat-sheet.md
development/repository.md

master->main
part of https://github.com/supercollider/supercollider/issues/5251

Update terminology usage and branch names

---

_config.yml

config: fix jekyll build error

---

Gemfile

I need this to build the page locally under macOS with Ruby 3 from homebrew.
Honestly, I'm not sure if this has any side effects. Please review carefully.

Gemfile: add webrick

---

_posts/2021-09-05-supercollider-3.12.1.md

(I forgot to do this when updating downloads page)

Create "News" entry for SC 3.12.1

---

_data/downloads.yml
_posts/2023-02-19-supercollider-3.13.0.md

Also added a post to show up in the "News" section

Update downloads for SC 3.13.0

---

_data/gallery.yml
_posts/2011-04-19-the-supercollider-book.md

Noticed this broken link on your website. Cool URIs don't change but MIT has changed the url...

Update mitpress.mit.edu broken link

---

_includes/default/head.html
_includes/default/navbar.html

Fixes #284 
See
https://github.com/user-attachments/assets/d0cfed4c-94ab-406f-b052-00affeca51c6

Fix show/hide functionality to burger menu button

---

assets/css/main.scss

See e.g. https://supercollider.github.io/releases/2025/03/15/supercollider-3.13.1.html - current
vs new

Fix vertical height layout

---

community.md

fix scsynth.org address

---

_data/downloads.yml

Fixes 
Regression of https://github.com/supercollider/supercollider.github.io/pull/304

Set current version to 3.14.0
