Gemfile
According to the bundler docs - http://bundler.io/v1.5/gemfile_ruby.html - the ruby version directive is for strict binary compatibility, and is therefore too strict for our purposes. In fact we need any version of ruby which can run the github-pages gem, which is already enforced by the following line in the Gemfile.
Installing a particular sub-point revision of ruby is otherwise an unnecessary additional barrier to participation, no?
=> Remove ruby 2.0.0 strict version dependency

_includes/download.md
- Changes OSX download link to point to 3.7.1
- Adds Windows links for 3.7
I didn't know where the Linux source should point to, so that's unchanged
=> Adjust download page to 3.7.1

_config.yml
I cannot test "on site" if this works. Locally for me it does (whereas pygments: true breaks)
Note: while pygments 2.1 does seem to contain a SC lexer, you do not get it via the gem "pygments.rb". Probably the pygments version contained is too old. Is there a way to know if the pygments used on the Github site already contains it?
=> Update _config.yml to use pygments

atom.xml, community/code-of-conduct.md
@crucialfelix `atom` automagically fixed the trailing whitespaces, real change is the YAML header.
Second commit is unrelated but I was too lazy to submit a 2nd PR for that ;)
=> Code of conduct fix

_includes/download.md, css/main.css
A couple of small changes:
- fix icon
- reorder download links (modern first) for clarity sake
- remove unnecessary `h4` margin-top
=> Download page slight improvements

index.md
The overall idea here is to make the first impression more appealing to the computer music crowd. Also clearly delineate scsynth/sclang/scide right off the bat, because that distinction is fundamental to SC.
I don't have the exact numbers of UGens for core and sc3-plugins, please fix and replace the 666's. also the sclang description is unfinished.
if you have push access to this repo feel free to commit your changes directly to this branch.
=> Rewrite main page description

development/building-raspberrypi.md
Add a line to step 4 of standard Raspbian Jessie install for users having issues with tooltip text being illegible (White text on yellow background).  By running "scide -style=gtkrc" Qt style is mapped to gtk standard colors and the white text becomes black. No other interface changes observed.  This is a workaround for a currently open issue in SC 3.7 and 3.8.
=> Add fix for issues with tooltip in ide

_includes/download.md
Link was pointing to the 3.7.2 linux source code.
=> Change linux source code link to 3.8.0

_layouts/default.html
This what the nav bar currently looks like for me on Firefox, Chrome, and Safari. I know there are bigger fish to fry but since this is a tiny design bug that could be easily fixed, I just did it quick as a way to get familiar with this repo. :)
=> Give nav bar badges more room so they don't internally wrap

development/bugs.md
There is no need to have this information here. It will constantly become outdated. Better to remove it.
=> Remove reference to current milestone

development/building-beagleboneblack.md
big rewrite for debian stretch and sc3.9.  many things simplified due to the new gcc 6.3.0, added info about sc3-plugins, removed old wheezy etc
=> update bbb build instructions for stretch 3.9

tutorials/index.md
- Fixed some broken links ("other bundled tutorials" and David Cottle's)
- Added Ruviaro's "A Gentle Guide.."
- Added Fieldsteel's YouTube series
- Corrected title of Cottle's tutorial
- Added author's names for "Getting Started with SC" and  improved wording a bit.
I haven't checked the other links on the page. I only looked at the "Recommended Introductory Tutorials" section.
=> Tutorial page improvements

_includes/download.md
- Use dots for `ul` instead of icons - semantically, the download icon should only be used for links that will begin a download
- Expand out `ul`s to match formatting of the rest of the document
=> Downloads page: use dots instead of icons

_includes/download.md
SuperCollider is being automatically built in the Open Build Service (in fact not just for openSUSE, but for Debian, Fedora, and Ubuntu too).
=> add a link for openSUSE downloads

_includes/download.md
Windows 3.9.0 32-bit build doesn't have supernova
=> Update downloads page

development/building.md
I felt the **Building From Source** page was in need of some love.
- Removed the mention of ubuntu with regards to BeagleBone Black (guide is for debian only).
- Removed link to iphone readme (gives the impression this is a supported platform)
- Remove "etc..."
- Renamed "Building on embedded linux ..." to "Community provided build guides"
- Added links to ubuntu and fedora guides from SC wiki 
- Removed links to Rpi and BBB websites and made names **bold**
**note** If anyone knows of a well written 3rd-party **macOS** or **Windows** build guide, please let me know.
Please review and suggest improvements ✨
=> Improve Building From Source page

css/main.css, index.md
This commit replaces the second front page example with a new original
one, titled "60 Hz Gabber Rave 1995." The previous example had to go
since it used the Atari2600 UGen, which is not in either core or
sc3-plugins.
The example is my original work. I release it under the public domain.
=> Replace second front page example

index.md
I find the example still a bit too close to the clipping point. This lowers the amplitude a bit.
=> Lower example volume for even more headroom

_includes/download.md
These won't work yet, but once https://github.com/supercollider/supercollider/pull/3441 is merged and then 3.9 merged to develop, we can link to these!
=> Add download links for windows dev builds

development/building-raspberrypi.md
removed the steps for moving GUI files, fixed a serious problem with autostart.sh, removed some unneeded libraries.
=> RPi instruction updates for 3.9.1

development/building-raspberrypi.md
changes header wording to clarify intended usage - instructions are only for >= 3.9.1. also say "latest" instead of "3.9" to avoid documentation decay
=> Update rpi build instructions

index.md
The Flickr group shouldn't be linked to as a official social media page for SC. Nice photos though!
=> Remove link to Flickr SC group

index.md
This PR removes the list of **other scsynth clients** from the bottom of the homepage. This info has no place being there, and is provided in the **Systems interfacing with SC** page.
=> Remove 'other scsynth clients' from homepage

index.md
This link is too close to the top menu "Download" link to be useful. If we want the downloads to be more prominent, we should move the download section higher up.
=> Remove redundant download link

Gemfile
Some Linux systems are unable to build the SC website locally due to Jekyll not finding JSON. The fix appears to be including 'json' in the site's Gemfile. I figure setting it to '>=2.0' will be fine.
=> Add JSON to Gemfile

_includes/download.md, css/main.css, download.md, index.md
This PR redesigns the `Download` page and changes the `_includes/download.md` to only contain the download links table. This makes the homepage download section more concise. 
The CSS styling related to `download` was commented out. This was causing a box to appear around markdown style headers called "Download". Also, I think it looks better without the box around the download section.
I can do the lower section of the Download page in markdown in a separate PR.
=> Download redesign

tutorials/index.md
I was browsing the tutorials page on the Supercollider site and noticed that the "Computer Music with examples in SuperCollider 3" by David Cottle led to a missing file. I found a new server that hosts the same file. This patch updates that link on the tutorial to point to the accessible file.
For reference:
[Old link](http://camil.music.illinois.edu/Classes/404A3/Documents/CottleSC3.pdf) (broken)
[New link](http://rhoadley.net/courses/tech_resources/supercollider/tutorials/cottle/CMSC7105.pdf)
=> Fix links in tutorial/index.md

community/code-of-conduct.md, community/mailing-lists.md, community/papers.md, community/sc140.md, community/supercollider-symposium.md, community/systems-interfacing-with-sc.md
On the _Wiki_ page, the __Community__ section will now list pages in the following order:
* Community
* Code of conduct
* Mailing Lists
* blogs and sites
* Systems interfacing with SC
* sc140
* SuperCollider Symposium
* Academic Papers
The main difference is that the CoC is up top, followed by the mailing list. There's no ideal ordering for the rest of the pages, I think.
=> Redo Wiki Community section ordering

index.md
Just a small fix to the Code of Conduct link on the homepage.
=> [Homepage] update link to CoC

_includes/download.md, _posts/2018-11-25-supercollider-3.10.0.md, download.md
- remove sc3-plugins from windows downloads (link is on page)
- remove versions before 3.7.2 from download links
- remove info about 3.7.2 vs 3.6.6 (3.6.6 no longer linked on page)
- add 3.10.0 links
- correct spelling of sc3-plugins
- make external links open in new tab/window
- redirect sc3-plugins link to new site
several of these points are up for discussion. i just thought the
windows release links were getting crowded with links to sc3-plugins,
and there's a link to it below anyway.
=> [WIP] Update downloads page for 3.10.0

development/building-raspberrypi.md
scide instructions still on 3.9 because of qtwebengine5  issue with raspbian stretch https://github.com/supercollider/supercollider/issues/4010
=> raspberry headless update instructions for 3.10

index.md
Fixes #192 
The link to Server Command Reference was missing `.html`
=> Fix broken link to Server Cmd Reference

_includes/download.md
_includes/download.md: Adding link to Arch Linux package. Removing redundancy in link names. Moving AUR PKGBUILD to bleeding edge (because that's what it is).
=> Updating/extending Linux package download links

_includes/download.md, download.md
this is a part of implementing github.com/supercollider/rfcs/pull/1
=> add download page info on platform support

_includes/download.md
I was trying to minimize the noise on the download page, please let me know what you think.
Particularly I wonder whether the asterisk mark works for this and if linking it to the footnote makes sense. Also, maybe it would be better to just have a single footnote for all/both platforms?
=> download page: clarify supernova builds

_includes/download.md
_includes/download.md:
The source tarball name has been generalized with
https://github.com/supercollider/supercollider/pull/4837 and is now not
Linux specific anymore.
The naming scheme is now 'SuperCollider-<version>-Source.tar.bz2'.
=> Fixing source tarball naming

_includes/download.md
After a request from users on the forum, here is a proposal for adding a warning for ear damage under macos downoad page, with recommendation to install the SafetyNet quark, and a link to Quarks installation instructions.
Forum discussion: https://scsynth.org/t/way-to-limit-maximum-output-volume
Issue with CoreAudio not clipping/limit the output range: https://github.com/supercollider/supercollider/issues/4894
=> add macos ear damage warning

_includes/download.md
i also removed the 3.11.0 links; since the 3.11.2 release covers back to macOS 10.10 now there's not much of a reason
to keep the 3.11.0 artifacts up. i think it may have been a mistake originally anyway.
=> update downloads page for 3.11.2

_includes/download.md
See https://github.com/supercollider/supercollider/issues/5387
Vista hasn't been supported in Qt since 5.9 at least: https://doc.qt.io/archives/qt-5.9/supported-platforms.html
So it's no surprise to me that they are using API features that require Windows 7
=> remove Vista from list of supported platforms

_posts/2019-01-17-supercollider-3.10.1.md, _posts/2019-02-08-supercollider-3.10.2.md, _posts/2019-08-30-supercollider-3.10.3.md, _posts/2020-01-16-supercollider-3.10.4.md, _posts/2020-03-22-supercollider-3.11.0.md, _posts/2020-04-21-supercollider-3.11.1.md, _posts/2020-11-14-supercollider-3.11.2.md, _posts/2021-08-02-supercollider-3.12.0.md
I've updated the news archive with rudimentary entries for past releases (minor and bugfix), as well as for the current 3.12.0 release. Let me know if anything needs changing.
I've built the site locally and spot-checked it, looks fine to me.
=> Update news archive

_data/gallery.yml
added missing `d` in name/url and added project specific #target
=> fix: greenwashing link

links.md
redirect `Documentation` to `docs.supercollider.online`
=> Update links.md to direct Documentation to docs.supercollider.online

.github/workflows/actions.yml
Maybe it is good to build the website on each request, just to be aware if it breaks anything.
Especially useful in combination with #282
=> Add CI for pull requests

_data/nav.yml
Proposal to add a link to the official docs in the navbar - I think this is rather common among project websites.
With the change it would look like this.
=> Add link to docs in navbar

_data/downloads.yml
As requested in https://github.com/supercollider/supercollider.github.io/issues/285#issuecomment-2599509928
Will be removed b/c we don't upload a 32 bit windows build anymore, see https://github.com/supercollider/supercollider/commit/f86408abd154fa50cb1d44a28aed7561281b6ed6
=> Remove 32 bit windows nightly download

_data/downloads.yml
Implements https://github.com/supercollider/supercollider.github.io/issues/285
This needs to be coordinated with https://github.com/supercollider/supercollider/pull/6593
=> Add download link for nightly macOS arm build

assets/css/main.scss
=> Make audio player take full width

_includes/features.md
I think if we start talking about *server* we should mention that this scsynth is not a webserver.
I also added that scsynth has multiple ways to interact with (aka client implementations), emphasizing the "polyglottness" of the SuperCollider ecosystem :)
While we are at it, I'd also like to show some love for supernova :)
Decided to first mention the features, than its origins - hope this is fine w/ everyone.
I am unsure if this isn't too much technical mumbo-jumbo upfront - maybe someone can give some feedback here? Yet we were already talking about servers and interpreted languages which probably only people w/ IT background could relate to.
=> Add more information on feature post

assets/css/main.scss
Currently
w/ this PR
edit: PR screenshot uses dark theme and has #291 not included, although this would be included after a merge
=> Make Snippet take full width

_includes/default/navbar.html
We have a light/dark button but it was not attached to an icon and therefore not clickable. This PR fixes this.
Light theme
Dark theme
=> Fix toggle theme button

_includes/default/head.html, assets/css/main.scss, downloads.md
As platforms are more mutually exclusive I thought it would be better to organize the downloads in tabs instead of a long list
[Current](https://supercollider.github.io/downloads)
... long scrolling
This PR
=> Group downloads via tabs

_data/nav.yml, community.md
Add a link to the official mastodon account of SuperCollider located @ https://social.toplap.org/@supercollider/
Currently I have access to the account and it is associated with my private mail, but I am happy to share this account w/ other devs or community managers <3
Changes as screenshot
=> Add mastodon link
